import type { GlobalThemeOverrides } from 'naive-ui'

export const lightThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#4f46e5',
    primaryColorHover: '#6366f1',
    primaryColorPressed: '#4338ca',
    primaryColorSuppl: '#a5b4fc',
    successColor: '#16a34a',
    successColorHover: '#22c55e',
    successColorPressed: '#15803d',
    warningColor: '#d97706',
    warningColorHover: '#f59e0b',
    warningColorPressed: '#b45309',
    errorColor: '#dc2626',
    errorColorHover: '#ef4444',
    errorColorPressed: '#b91c1c',
    infoColor: '#0891b2',
    infoColorHover: '#06b6d4',
    infoColorPressed: '#0e7490',
    textColorBase: '#0f172a',
    textColor1: '#0f172a',
    textColor2: '#334155',
    textColor3: '#64748b',
    textColorDisabled: '#94a3b8',
    placeholderColor: '#94a3b8',
    borderColor: '#e2e8f0',
    dividerColor: '#e2e8f0',
    inputColor: '#ffffff',
    bodyColor: '#f8fafc',
    cardColor: '#ffffff',
    modalColor: '#ffffff',
    popoverColor: '#ffffff',
    tableColor: '#ffffff',
    tableHeaderColor: '#f8fafc',
    hoverColor: '#f1f5f9',
    borderRadius: '8px',
    borderRadiusSmall: '6px',
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    fontSize: '14px',
    fontSizeMini: '12px',
    fontSizeTiny: '12px',
    fontSizeSmall: '13px',
    fontSizeMedium: '14px',
    fontSizeLarge: '15px',
    fontSizeHuge: '16px',
    heightMini: '28px',
    heightTiny: '30px',
    heightSmall: '34px',
    heightMedium: '36px',
    heightLarge: '40px',
    heightHuge: '44px',
  },
  Card: {
    borderRadius: '12px',
    paddingMedium: '20px',
    paddingLarge: '24px',
    titleFontWeight: '600',
    titleFontSizeMedium: '16px',
    titleFontSizeLarge: '18px',
    borderColor: '#e2e8f0',
    color: '#ffffff',
  },
  Button: {
    borderRadiusMedium: '8px',
    borderRadiusSmall: '6px',
    borderRadiusLarge: '10px',
    heightMedium: '36px',
    heightSmall: '30px',
    heightLarge: '40px',
    fontWeightStrong: '600',
  },
  DataTable: {
    thColor: '#f8fafc',
    thTextColor: '#64748b',
    thFontWeight: '600',
    tdColor: '#ffffff',
    tdTextColor: '#334155',
    borderColor: '#f1f5f9',
    thPaddingMedium: '12px 16px',
    tdPaddingMedium: '12px 16px',
    borderRadius: '12px',
  },
  Menu: {
    borderRadius: '8px',
    itemTextColorActive: '#4f46e5',
    itemTextColorActiveHover: '#4f46e5',
    itemIconColorActive: '#4f46e5',
    itemIconColorActiveHover: '#4f46e5',
    itemColorActive: 'rgba(79, 70, 229, 0.08)',
    itemColorActiveHover: 'rgba(79, 70, 229, 0.12)',
    itemColorHover: '#f1f5f9',
  },
  Tabs: {
    tabTextColorActiveLine: '#4f46e5',
    tabTextColorHoverLine: '#6366f1',
    tabTextColorActiveBar: '#4f46e5',
    tabTextColorHoverBar: '#6366f1',
    barColor: '#4f46e5',
    tabFontWeightActive: '600',
  },
  Input: {
    borderRadius: '8px',
    borderHover: '1px solid #6366f1',
    borderFocus: '1px solid #4f46e5',
    boxShadowFocus: '0 0 0 2px rgba(79, 70, 229, 0.15)',
    heightMedium: '36px',
  },
  Tag: {
    borderRadius: '6px',
    fontSizeMedium: '12px',
  },
  Pagination: {
    itemBorderRadius: '6px',
  },
  Dialog: {
    borderRadius: '12px',
  },
  Notification: {
    borderRadius: '12px',
  },
  Message: {
    borderRadius: '8px',
  },
}

export const darkThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#6366f1',
    primaryColorHover: '#818cf8',
    primaryColorPressed: '#4f46e5',
    primaryColorSuppl: '#818cf8',
    textColorBase: '#f1f5f9',
    textColor1: '#f1f5f9',
    textColor2: '#cbd5e1',
    textColor3: '#94a3b8',
    textColorDisabled: '#64748b',
    placeholderColor: '#64748b',
    borderColor: '#334155',
    dividerColor: '#334155',
    inputColor: '#1e293b',
    bodyColor: '#0f172a',
    cardColor: '#1e293b',
    modalColor: '#1e293b',
    popoverColor: '#1e293b',
    tableColor: '#1e293b',
    tableHeaderColor: '#0f172a',
    hoverColor: '#334155',
    borderRadius: '8px',
    borderRadiusSmall: '6px',
  },
  Card: {
    borderRadius: '12px',
    paddingMedium: '20px',
    paddingLarge: '24px',
    titleFontWeight: '600',
    borderColor: '#334155',
    color: '#1e293b',
  },
  Button: {
    borderRadiusMedium: '8px',
    borderRadiusSmall: '6px',
    borderRadiusLarge: '10px',
    heightMedium: '36px',
  },
  DataTable: {
    thColor: '#0f172a',
    thTextColor: '#94a3b8',
    thFontWeight: '600',
    tdColor: '#1e293b',
    tdTextColor: '#cbd5e1',
    borderColor: '#334155',
    borderRadius: '12px',
  },
  Menu: {
    borderRadius: '8px',
    itemTextColorActive: '#818cf8',
    itemTextColorActiveHover: '#818cf8',
    itemIconColorActive: '#818cf8',
    itemIconColorActiveHover: '#818cf8',
    itemColorActive: 'rgba(99, 102, 241, 0.12)',
    itemColorActiveHover: 'rgba(99, 102, 241, 0.18)',
    itemColorHover: '#334155',
  },
  Tabs: {
    tabTextColorActiveLine: '#818cf8',
    tabTextColorHoverLine: '#a5b4fc',
    tabTextColorActiveBar: '#818cf8',
    tabTextColorHoverBar: '#a5b4fc',
    barColor: '#818cf8',
    tabFontWeightActive: '600',
  },
  Input: {
    borderRadius: '8px',
    borderHover: '1px solid #818cf8',
    borderFocus: '1px solid #6366f1',
    boxShadowFocus: '0 0 0 2px rgba(99, 102, 241, 0.2)',
  },
}
