import type { GlobalThemeOverrides } from 'naive-ui'

export const lightThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#176392',
    primaryColorHover: '#2f7cae',
    primaryColorPressed: '#0d4b72',
    primaryColorSuppl: '#74addf',
    successColor: '#12b76a',
    successColorHover: '#35c987',
    successColorPressed: '#0f9f5c',
    warningColor: '#d97706',
    warningColorHover: '#f59e0b',
    warningColorPressed: '#b45309',
    errorColor: '#ff4d4f',
    errorColorHover: '#ff7476',
    errorColorPressed: '#e64447',
    infoColor: '#00b7c9',
    infoColorHover: '#34ccdb',
    infoColorPressed: '#0098ab',
    textColorBase: '#102a43',
    textColor1: '#102a43',
    textColor2: '#334e68',
    textColor3: '#627d98',
    textColorDisabled: '#9fb3c8',
    placeholderColor: '#829ab1',
    borderColor: '#d8e2ed',
    dividerColor: '#d8e2ed',
    inputColor: '#ffffff',
    bodyColor: '#eef3f8',
    cardColor: '#ffffff',
    modalColor: '#ffffff',
    popoverColor: '#ffffff',
    tableColor: '#ffffff',
    tableHeaderColor: '#f4f8fc',
    hoverColor: '#e7eef6',
    borderRadius: '10px',
    borderRadiusSmall: '6px',
    fontFamily: "'Avenir Next', 'PingFang SC', 'Hiragino Sans GB', 'Source Han Sans SC', 'Microsoft YaHei', sans-serif",
    fontSize: '14px',
    fontSizeMini: '12px',
    fontSizeTiny: '12px',
    fontSizeSmall: '13px',
    fontSizeMedium: '14px',
    fontSizeLarge: '15px',
    fontSizeHuge: '16px',
    heightMini: '28px',
    heightTiny: '30px',
    heightSmall: '34px',
    heightMedium: '36px',
    heightLarge: '40px',
    heightHuge: '44px',
  },
  Card: {
    borderRadius: '14px',
    paddingMedium: '20px',
    paddingLarge: '24px',
    titleFontWeight: '650',
    titleFontSizeMedium: '16px',
    titleFontSizeLarge: '18px',
    borderColor: '#d8e2ed',
    color: '#ffffff',
  },
  Button: {
    borderRadiusMedium: '8px',
    borderRadiusSmall: '6px',
    borderRadiusLarge: '10px',
    heightMedium: '36px',
    heightSmall: '30px',
    heightLarge: '40px',
    fontWeightStrong: '600',
  },
  DataTable: {
    thColor: '#f4f8fc',
    thTextColor: '#486581',
    thFontWeight: '600',
    tdColor: '#ffffff',
    tdTextColor: '#334e68',
    borderColor: '#e7eef6',
    thPaddingMedium: '12px 16px',
    tdPaddingMedium: '12px 16px',
    borderRadius: '12px',
  },
  Menu: {
    borderRadius: '8px',
    itemTextColorActive: '#176392',
    itemTextColorActiveHover: '#176392',
    itemIconColorActive: '#176392',
    itemIconColorActiveHover: '#176392',
    itemColorActive: 'rgba(23, 99, 146, 0.11)',
    itemColorActiveHover: 'rgba(23, 99, 146, 0.14)',
    itemColorHover: '#e7eef6',
  },
  Tabs: {
    tabTextColorActiveLine: '#176392',
    tabTextColorHoverLine: '#2f7cae',
    tabTextColorActiveBar: '#176392',
    tabTextColorHoverBar: '#2f7cae',
    barColor: '#176392',
    tabFontWeightActive: '600',
  },
  Input: {
    borderRadius: '10px',
    borderHover: '1px solid #2f7cae',
    borderFocus: '1px solid #176392',
    boxShadowFocus: '0 0 0 2px rgba(23, 99, 146, 0.16)',
    heightMedium: '36px',
  },
  Tag: {
    borderRadius: '6px',
    fontSizeMedium: '12px',
  },
  Pagination: {
    itemBorderRadius: '6px',
  },
  Dialog: {
    borderRadius: '12px',
  },
  Notification: {
    borderRadius: '12px',
  },
  Message: {
    borderRadius: '8px',
  },
}

export const darkThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#20aac0',
    primaryColorHover: '#34bfd2',
    primaryColorPressed: '#1b8ea2',
    primaryColorSuppl: '#63d4e3',
    textColorBase: '#e6f0fa',
    textColor1: '#e6f0fa',
    textColor2: '#bdd0e3',
    textColor3: '#86a2bf',
    textColorDisabled: '#5f7a94',
    placeholderColor: '#6f8ca9',
    borderColor: '#1e3c58',
    dividerColor: '#1e3c58',
    inputColor: '#10283e',
    bodyColor: '#071523',
    cardColor: '#0d2236',
    modalColor: '#0d2236',
    popoverColor: '#0d2236',
    tableColor: '#0d2236',
    tableHeaderColor: '#0b1d2e',
    hoverColor: '#14314c',
    borderRadius: '10px',
    borderRadiusSmall: '6px',
    fontFamily: "'Avenir Next', 'PingFang SC', 'Hiragino Sans GB', 'Source Han Sans SC', 'Microsoft YaHei', sans-serif",
  },
  Card: {
    borderRadius: '14px',
    paddingMedium: '20px',
    paddingLarge: '24px',
    titleFontWeight: '600',
    borderColor: '#1e3c58',
    color: '#0d2236',
  },
  Button: {
    borderRadiusMedium: '8px',
    borderRadiusSmall: '6px',
    borderRadiusLarge: '10px',
    heightMedium: '36px',
  },
  DataTable: {
    thColor: '#0b1d2e',
    thTextColor: '#86a2bf',
    thFontWeight: '600',
    tdColor: '#0d2236',
    tdTextColor: '#bdd0e3',
    borderColor: '#1e3c58',
    borderRadius: '12px',
  },
  Menu: {
    borderRadius: '8px',
    itemTextColorActive: '#34bfd2',
    itemTextColorActiveHover: '#34bfd2',
    itemIconColorActive: '#34bfd2',
    itemIconColorActiveHover: '#34bfd2',
    itemColorActive: 'rgba(32, 170, 192, 0.16)',
    itemColorActiveHover: 'rgba(32, 170, 192, 0.2)',
    itemColorHover: '#14314c',
  },
  Tabs: {
    tabTextColorActiveLine: '#34bfd2',
    tabTextColorHoverLine: '#63d4e3',
    tabTextColorActiveBar: '#34bfd2',
    tabTextColorHoverBar: '#63d4e3',
    barColor: '#34bfd2',
    tabFontWeightActive: '600',
  },
  Input: {
    borderRadius: '10px',
    borderHover: '1px solid #34bfd2',
    borderFocus: '1px solid #20aac0',
    boxShadowFocus: '0 0 0 2px rgba(32, 170, 192, 0.24)',
  },
}
