import type { GlobalThemeOverrides } from 'naive-ui'

export const lightThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#C9A96E',
    primaryColorHover: '#D4BA82',
    primaryColorPressed: '#B08D4E',
    primaryColorSuppl: '#E5D5B0',
    successColor: '#2BA471',
    successColorHover: '#3DB882',
    successColorPressed: '#1F8A5C',
    warningColor: '#D4910A',
    warningColorHover: '#E5A525',
    warningColorPressed: '#B07A08',
    errorColor: '#E54D42',
    errorColorHover: '#F06B62',
    errorColorPressed: '#C73B31',
    infoColor: '#71717A',
    infoColorHover: '#A1A1AA',
    infoColorPressed: '#52525B',
    textColorBase: '#18181B',
    textColor1: '#18181B',
    textColor2: '#52525B',
    textColor3: '#71717A',
    textColorDisabled: '#A1A1AA',
    placeholderColor: '#A1A1AA',
    borderColor: '#D4D4D8',
    dividerColor: '#E4E4E7',
    inputColor: '#ffffff',
    bodyColor: '#F4F4F5',
    cardColor: '#ffffff',
    modalColor: '#ffffff',
    popoverColor: '#ffffff',
    tableColor: '#ffffff',
    tableHeaderColor: '#FAFAFA',
    hoverColor: '#F4F4F5',
    borderRadius: '10px',
    borderRadiusSmall: '6px',
    fontFamily: "'Avenir Next', 'PingFang SC', 'Hiragino Sans GB', 'Source Han Sans SC', 'Microsoft YaHei', sans-serif",
    fontSize: '14px',
    fontSizeMini: '12px',
    fontSizeTiny: '12px',
    fontSizeSmall: '13px',
    fontSizeMedium: '14px',
    fontSizeLarge: '15px',
    fontSizeHuge: '16px',
    heightMini: '28px',
    heightTiny: '30px',
    heightSmall: '34px',
    heightMedium: '36px',
    heightLarge: '40px',
    heightHuge: '44px',
  },
  Card: {
    borderRadius: '14px',
    paddingMedium: '20px',
    paddingLarge: '24px',
    titleFontWeight: '650',
    titleFontSizeMedium: '16px',
    titleFontSizeLarge: '18px',
    borderColor: '#E4E4E7',
    color: '#ffffff',
  },
  Button: {
    borderRadiusMedium: '8px',
    borderRadiusSmall: '6px',
    borderRadiusLarge: '10px',
    heightMedium: '36px',
    heightSmall: '30px',
    heightLarge: '40px',
    fontWeightStrong: '600',
    borderHover: '1px solid #C9A96E',
    borderFocus: '1px solid #C9A96E',
    boxShadowFocus: '0 0 0 2px rgba(201, 169, 110, 0.15)',
  },
  DataTable: {
    thColor: '#FAFAFA',
    thTextColor: '#52525B',
    thFontWeight: '600',
    tdColor: '#ffffff',
    tdTextColor: '#52525B',
    borderColor: '#E4E4E7',
    thPaddingMedium: '12px 16px',
    tdPaddingMedium: '12px 16px',
    borderRadius: '12px',
  },
  Menu: {
    borderRadius: '8px',
    itemTextColorActive: '#C9A96E',
    itemTextColorActiveHover: '#C9A96E',
    itemIconColorActive: '#C9A96E',
    itemIconColorActiveHover: '#C9A96E',
    itemColorActive: 'rgba(201, 169, 110, 0.10)',
    itemColorActiveHover: 'rgba(201, 169, 110, 0.16)',
    itemColorHover: '#F4F4F5',
  },
  Tabs: {
    tabTextColorActiveLine: '#C9A96E',
    tabTextColorHoverLine: '#D4BA82',
    tabTextColorActiveBar: '#C9A96E',
    tabTextColorHoverBar: '#D4BA82',
    barColor: '#C9A96E',
    tabFontWeightActive: '600',
  },
  Input: {
    borderRadius: '10px',
    borderHover: '1px solid #C9A96E',
    borderFocus: '1px solid #C9A96E',
    boxShadowFocus: '0 0 0 2px rgba(201, 169, 110, 0.15)',
    heightMedium: '36px',
  },
  Tag: {
    borderRadius: '6px',
    fontSizeMedium: '12px',
  },
  Pagination: {
    itemBorderRadius: '6px',
  },
  Dialog: {
    borderRadius: '12px',
  },
  Notification: {
    borderRadius: '12px',
  },
  Message: {
    borderRadius: '8px',
  },
}

export const darkThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#C9A96E',
    primaryColorHover: '#D4BA82',
    primaryColorPressed: '#B08D4E',
    primaryColorSuppl: '#E5D5B0',
    textColorBase: '#EAEAEE',
    textColor1: '#EAEAEE',
    textColor2: '#A1A1AA',
    textColor3: '#71717A',
    textColorDisabled: '#52525B',
    placeholderColor: '#52525B',
    borderColor: '#3A3A3E',
    dividerColor: '#2A2A2E',
    inputColor: '#18181B',
    bodyColor: '#09090B',
    cardColor: '#141416',
    modalColor: '#141416',
    popoverColor: '#141416',
    tableColor: '#141416',
    tableHeaderColor: '#0F0F10',
    hoverColor: '#1C1C1F',
    borderRadius: '10px',
    borderRadiusSmall: '6px',
    fontFamily: "'Avenir Next', 'PingFang SC', 'Hiragino Sans GB', 'Source Han Sans SC', 'Microsoft YaHei', sans-serif",
  },
  Card: {
    borderRadius: '14px',
    paddingMedium: '20px',
    paddingLarge: '24px',
    titleFontWeight: '600',
    borderColor: '#2A2A2E',
    color: '#141416',
  },
  Button: {
    borderRadiusMedium: '8px',
    borderRadiusSmall: '6px',
    borderRadiusLarge: '10px',
    heightMedium: '36px',
    textColorText: '#A1A1AA',
    textColorTextHover: '#D4BA82',
    textColorGhost: '#A1A1AA',
    textColorGhostHover: '#D4BA82',
    borderDefault: '1px solid #3A3A3E',
    borderHover: '1px solid #C9A96E',
    colorDefault: '#1C1C1F',
    colorHover: '#222226',
  },
  DataTable: {
    thColor: '#0F0F10',
    thTextColor: '#71717A',
    thFontWeight: '600',
    tdColor: '#141416',
    tdTextColor: '#A1A1AA',
    borderColor: '#2A2A2E',
    borderRadius: '12px',
  },
  Menu: {
    borderRadius: '8px',
    itemTextColorActive: '#D4BA82',
    itemTextColorActiveHover: '#D4BA82',
    itemIconColorActive: '#D4BA82',
    itemIconColorActiveHover: '#D4BA82',
    itemColorActive: 'rgba(212, 186, 130, 0.10)',
    itemColorActiveHover: 'rgba(212, 186, 130, 0.16)',
    itemColorHover: '#1C1C1F',
  },
  Tabs: {
    tabTextColorActiveLine: '#D4BA82',
    tabTextColorHoverLine: '#E5D5B0',
    tabTextColorActiveBar: '#D4BA82',
    tabTextColorHoverBar: '#E5D5B0',
    barColor: '#D4BA82',
    tabFontWeightActive: '600',
  },
  Input: {
    borderRadius: '10px',
    borderHover: '1px solid #52525B',
    borderFocus: '1px solid #D4BA82',
    boxShadowFocus: '0 0 0 2px rgba(212, 186, 130, 0.15)',
  },
}
